---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/JamesOBenson/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - git
  - go
  - hub
  - httpie
  - iperf
  - monit
  - nmap
  - ssh-copy-id
  - cowsay
  - openssl
  - pv
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
 
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - xquartz
  - cheatsheet
  - coconutbattery
  - docker
  - dropbox
  # - fing # Download link keeps getting changed, d'oh!
  - filezilla
  - firefox
  - google-chrome
  - google-hangouts
  - google-backup-and-sync
  - handbrake
  - inkscape
  - iterm2
  - itsycal
  - keepassx
  - keka
  - limechat
  - macvim
  - megasync
  - onedrive
  - sublime-text
  - teamviewer
  - textmate
  - tigervpn
  - transmission
  - unetbootin
  # - vagrant # SHA key may not be valid!
  - virtualbox
  - virtualbox-extension-pack
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
